### ISSUE TITLE
Improve Ethereum and Bitcoin metrics and diagnostics

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#3608]
The client exposes the Ethereum connectivity metric which is helpful to diagnose some problems with the connection but it is not enough to say if the client is up to date with the global Ethereum state (it has access to the chain tip). 

For Bitcoin, we do not have the Electrum connectivity metric at all.

We could:
- [x] Add Ethereum diagnostic reading the most recent Ethereum block number.
- [x] Add Electrum connectivity metric.
- [x] Add Electrum diagnostic reading the most recent Bitcoin block number.
- [x] Update Grafana dashboard at status.threshold.network to include Ethereum and Bitcoin connectivity metrics for nodes.
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/keep-core/pull/3637
- [ ] https://github.com/keep-network/keep-core/pull/3648
- [ ] https://github.com/keep-network/keep-core/pull/3705
- [ ] https://github.com/keep-network/keep-core/pull/3708
```

**Comment by pdyraga** [comment]
@tomaszslabon Please take care of updating Grafana once this version is deployed to testnet/mainnet.

**Comment by tomaszslabon** [comment]
In #3705 we updated the test Grafana dashboard with BTC Connectivity and ETH Connectivity.
The updated dashboard can be seen here: https://monitoring.test.threshold.network.
Only the test dashboard was updated.

Things to consider in the future:
1) Update the production Grafana dashboard with BTC Connectivity and ETH Connectivity in the similar manner.
    (must be done by somebody with edit privileges cc @pdyraga, @nkuba).
2) Discuss if we should display Latest ETH block and Latest BTC block in the dashboard.
    If we want to display them, we need to move these two measurements from the `\diagnostics` endpoint  into `\metrics`   so that it can be picked by Prometheus.
