### ISSUE TITLE
EPIC: Sweeping v1

### ISSUE THREAD

**Issue by erdogan** [keep-network/keep-core#3627]
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/keep-core/issues/3563
- [ ] https://github.com/keep-network/keep-core/issues/3615
- [ ] https://github.com/keep-network/keep-core/issues/3611
- [ ] https://github.com/keep-network/keep-core/issues/3610
- [ ] Announce
```
