### ISSUE TITLE
Implement moving funds commitment submission

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/keep-core#3733]
This issue is about implementing the moving funds commitment mechanism in the client. Long story short, wallet signers must agree on where funds should be sent to and submit such a commitment to the `Bridge`. The `Bridge` enforces a specific number of target wallets that must be chosen. The moving funds wallet should always start picking from the latest wallet and go backward. How wallet signers agree on the commitment should be discussed and decided upon implementation.
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/tbtc-v2/pull/757
- [ ] https://github.com/keep-network/tbtc-v2/pull/765
- [ ] https://github.com/keep-network/tbtc-v2/pull/762
- [ ] https://github.com/keep-network/keep-core/pull/3748
```
