### ISSUE TITLE
Reduce overhead around DKG

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/keep-core#3770]
The extension of the beta operators set made it clear that the current DKG process is resource-heavy and problematic for operators. The current retry scheme is inefficient, a huge amount of network traffic is generated, and logs are often clunky. This task aims to improve the situation.
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/keep-core/pull/3771
- [ ] https://github.com/keep-network/keep-core/pull/3773
- [ ] https://github.com/keep-network/keep-core/pull/3776
- [ ] https://github.com/keep-network/keep-core/pull/3777
```
