### ISSUE TITLE
Optimize deposit sweeping

### ISSUE THREAD

**Issue by lukasz-zimnoch** [keep-network/keep-core#3802]
The tBTC system observes an increase in the deposit count. The current configuration of the deposit sweep process experiences congestion and the time-to-sweep of a single deposit is extended to far more than the expected 48 hours. Although this is not a critical problem due to a long refund time, we need to optimize the deposit sweep process and make it able to handle significant deposit numbers gracefully.
```[tasklist]
### Tasks
- [ ] https://github.com/keep-network/keep-core/pull/3803
- [ ] https://github.com/keep-network/keep-core/pull/3804
- [ ] https://github.com/keep-network/keep-core/pull/3805
```
