### ISSUE TITLE
DKG on-chain result publication without voting

### ISSUE THREAD

**Issue by pdyraga** [keep-network/keep-core#625]
Based on the input from #623 we need to implement a new version of DKG result on-chain publication protocol.

#### Phase 13

Once the result has been determined, all participants evaluate the hash of their preferred result, sign the hash and broadcast the hash and a signature over it in the group broadcast channel. Each participant collects the signatures matching their preferred result, stores them along with the signers' member indices. All of this activity happens off-chain. 

If the signature of hash broadcasted off-chain is invalid, it should be rejected and not published on-chain. If multiple signatures from the same member on the same result are found, they should all be filtered-out before publishing on-chain.

#### Phase 14

When a participant becomes eligible to submit the result on-chain they submit if they have at least `H` signatures for that result (including their own). 

`P_1` is always eligible to submit result. `P_2` becomes eligible after `T_dkg + T_step` and remains eligible until result is accepted by chain. In other words, `P_n` becomes eligible after`T_dkg + (n-1) * T_step` and remains eligible until result is accepted by chain. If `P_1` is late and `P_2` tries to submit, whichever gets mined first wins and subsequent submissions are disregarded immediately to avoid burdening the loser with excess gas fees

When the result is submitted on-chain along with the signatures, the contract checks that there are at least `H` signatures or more, and that each signature is valid for the submitted result and the corresponding member ID. `H` is the honest majority - a constant for the given group size. Submissions containing duplicate signatures on the same result from the same member are rejected.

If the above checks pass, the result is considered canonical for the group. All other group members should abort publishing their results and no new result submissions will be accepted by the chain.

If the above checks do not pass, result is rejected.

If the result has been rejected and `P_2` became eligible, `P_2` can submit its result. Same checks are applied as for `P_1`. 

If no canonical result has been published until `T_dkg + N * T_step`, where `N` is the group size, DKG operation is marked as failed.

### Tasks

- [x] Off-chain result hash and signature broadcast protocol #633 (estimate: 2 days)
- [x] Off-chain result hash signing and on-chain signature verification #632 (estimate: 3 days)
- [x] Off-chain API for signing with Keep client's static key #634 (estimate: 3 days)
- [x] Off-chain group registration when quorum result is published to the chain #635 (estimate: 1 day)
- [x] Off-chain result publication #638 (estimate: 4 days)
- [x] On-chain submission eligibility check #641 (estimate: 2 days)
- [x] Improve off-chain block synchronization precision #640 (estimate: 2 days)
- [x] State machine updates to accommodate the new phases #639 (estimate: 2 days)
- [x] Document implementation in a form of RFC #636 (estimate: 2 days)
- [x] Validate key used for result hash signing #662 (unplanned)
- [x] Refactor DKG group membership code to allow for IA/DQ filtering in DKG P13 #698 (unplanned)

Estimate: 21 man-days in total

Flowdock discussion: https://www.flowdock.com/app/cardforcoin/tech/threads/vptITb99ElQPTHHkE9m-sEQmT3X
