### ISSUE TITLE
Introduce a generated command-line interface to contracts

### ISSUE THREAD

**Issue by Shadowfiend** [keep-network/keep-core#883]
Incidentally this wish was already mentioned in my aspirational help docs in #52.

The goal here is to provide a way to invoke our contracts from the Keep executable. We will do this using code generation, based on the same abstractions we're generating for the rest of the code to interact with the chain.

There's a secondary goal (not part of this issue) to extract this and all the other support generation code to a common repository that can be referenced from other repos like tBTC.

Steps here:
- [x] Extract a few common utilities. (#877)
- [x] Refactor contract generation to be easier to follow. (#878)
- [x] Implement commands for view-only/constant contract functions. (#880)
- [x] Extract some common flags and code for mutating contract functions. (#888)
- [x] Implement block targeting for constant contract functions. (#889)
- [x] Implement commands for mutating contract functions. (#890)
-  ~~Implement viewing of an already-executed transaction result.~~ You actually can't do this!

Additional possibilities:

- `--nonce <number>` flag to force a specific nonce?
-  `--address` flag to force an address to override existing config or possibly operate without config?
